### ISSUE TITLE
TS Error in ngrx/effects

### ISSUE THREAD

**Issue by qamukova** [IliaIdakiev/softuni-angular#12]
Поопражнявам се на един стар проект, но ми дава следната да я наречем 'грешка' в effect-а. Мисля, че ще ми е нужна малко помощ да оправя това:
**TS2322: Type ‘{ error: any; } & TypedAction<string>’ is not assignable to tape ‘ObservableInput<any>’. 
Property ‘[Symbol.iterator]’ is missing in type ‘{ error: any; } & TypedAction<string>’ but required in type ‘Iterable<any>’.
lib.es2015.iterable.d.ts(51, 5): ‘[Symbol.iterator]’ is declared here. 		                   catchError.d.ts(3, 81): The expected type **comes** from the return type of this signature.**

или 

**TS2322: Type ‘Observable<unknown>’ is not assignable to type ‘Observable<Action> | ((…args: any[]) => Observable<Action>)’. Type ‘Observable<unknown>’ is not assignable to type ‘Observable<Action>’. 
Property ‘type’ is missing in type ‘{}’ but required in type ‘Action’.
models.d.ts(2, 5): ‘type’ is declared here.							                                                effect_creator.d.ts(40, 198): The expected type comes from the return type of this signature.**

Това ми е effect-а:
`register$ = createEffect(() => this.actions$.pipe(
    ofType(AuthActions.register),
    switchMap((data) => this.authService.signUp(data).pipe(
      map(() => AuthActions.registerSuccess ),
      tap(() => this.router.navigate(['/login'])),
      catchError((err) => AuthActions.registerFailed({ error: err.error }))
    ))
  ));`

А това action-a: 
`export const register = createAction(
  ActionTypes.Register,
  props<{ username: string, password: string }>()
);
export const registerSuccess = createAction(
  ActionTypes.RegisterSuccess,
  props()
);
export const registerFailed = createAction(
  ActionTypes.RegisterFailed,
  props<{ error: any }>()
);`

**Comment by qamukova** [comment]
Сложих върнатото от catchError в масив и вече, не ми свети:
`catchError((err) => [AuthActions.registerFailed({ error: err.error })])`
Не зная дали това е правилното решение и подход, понеже не съм сигурна, какво точно се опитва TS да ми каже, което не съм описала или направила правилно?

**Comment by IliaIdakiev** [comment]
Принципно catchError оператора приема функция, която връща observable. В повечето случаи когато трябва да се върне observable може да се върне Iterable, а масивите в JS са точно са Iterable и за това грешката изчезва. Може да си представим, че това което се връща е observable създаден с from конструктор функцията `from([someObject])`.
