### ISSUE TITLE
Кеширане на данни с ngrx store

### ISSUE THREAD

**Issue by qamukova** [IliaIdakiev/softuni-angular#2]
Кой е правилният начин за кеширане на данни в store? Трябва ли да имаме допълнипелно пропърти в state-а, например cacheSomething? Или след request-а правим нещо с този Observable, използвайки някой от rxjs операторите?

**Comment by IliaIdakiev** [comment]
Не съм сигурен какво точно имаш предвид под кеширане. Това, което може да направиш ако не искаш всеки път да се зареждат данните е просто да проверяваш дали вече са даредени и само ако не са да се пусне action-а за зареждане.

**Comment by qamukova** [comment]
В такъв случуй правилно ли е и може ли тази проверка да се извърши в ефекта, понеже от там след заявка диспачвам action или някъде другаде трябва да се случи? А относно кеша имам впредвид, когато юзъра навигира в някакъв списък и отваря нещо , затваря го и пак се връща на списака от items да речем в рамките на някакво време, при всъко връщане към listItems да не прави нова заявка а да ги взема от някакъв кеш в стора, съхраняващ данните след първия направен call към сървара за този лист от items. Може и да не съм права,и да не е това добър начин но поне така си го представям. Не зная въобще може ли да се направи с ngrx?

**Comment by IliaIdakiev** [comment]
Няма проблем да е в ефекта и като цяло навсякъде където е необходимо. Принципно ние нямаме подобна практика за запазване на вече заредените данни, защото приложенията, които правим се ползват от множество потребители и винаги искаме информацията да е възможно най-опреснена и за това всеки път при влизане на страницата зареждаме данните, защото междувременно някой др потребител може да е извършил някакви промени.
